default:
  extensions:
    SilverStripe\BehatExtension\Extension:
      framework_path: ../framework
      screenshot_path: %behat.paths.base%/artifacts/screenshots
    SilverStripe\BehatExtension\MinkExtension:
      # Adjust this to your local environment
      base_url:  http://%BASE_URL%/
      default_session: selenium2
      javascript_session: selenium2
      selenium2:
        browser: firefox
        wd_host: http://%SELENIUM_HOST%:4444/wd/hub
